name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Build static site for GitHub Pages
      run: |
        mkdir -p gh-pages
        cp -r src/public/* gh-pages/
        echo "# MessageForge - Universal Message Forwarder" > gh-pages/README.md
        echo "" >> gh-pages/README.md
        echo "🚀 **Live Demo**: [Try MessageForge](https://vats98754.github.io/message-forwarder/)" >> gh-pages/README.md
        echo "" >> gh-pages/README.md
        echo "This is a demo version of MessageForge. For full functionality, clone and run locally with your API credentials." >> gh-pages/README.md
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./gh-pages
